---
<<<<<<< HEAD
=======

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false

>>>>>>> geerlingguy-master
user: jpaul
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes

dotfiles_repo: git@github.com:jayson/dotfiles.git
dotfiles_push_url: git@github.com:jayson/dotfiles.git
dotfiles_repo_local_destination: ~/projects/dotfiles

dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - gh
  - python
  - bat
  - ccat
  - coreutils
  - cfssl
  - ctags
  - dockutil
  - drone-cli
  - fzf
  - git
  - gh
  - gpg
  - httpie
  - htop
  - jq
  - kubernetes-cli
  - kubectx
  - k9s
  - mas
  - neofetch
  - neovim
  - node
  - ranger
  - python
  - rbenv
  - readline
  - ripgrep
  - ruby
  - sketchybar
  #- skhd
  - socat
  - stern
  - datawire/blackbird/telepresence
  - vim
  - watch
  - wget
  - wrk
  - zsh-history-substring-search
  #- yabai
  - zplug
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/homebrew-cask
  - homebrew/cask-fonts
  - FelixKratz/formulae

    # TODO: 
    #
    # curl https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.3/sketchybar-app-font.ttf > $HOME/Library/Fonts/sketchybar-app-font.ttf
# TODO: Rewrite this as a brew cask install loop. This is very broken with the moving around of the above taps.
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - discord
  - docker
  - fantastical
  - firefox
  - google-cloud-sdk
  - hammerspoon
  - iterm2
  - osxfuse
  - vagrant
  - font-hack-nerd-font
  - sf-symbols
  #- font-roboto-mono-nerd-font
  #- gpg-suite
  #- little-snitch
  #- micro-snitch
  #- vscode
  #- xquartz

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: "jaysonpaul@gmail.com"
mas_password: ""

osx_script: "/Users/jpaul/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

gem_packages:
  - name: bundler
    state: present  # present/absent/latest, default: present

composer_packages: []
npm_packages: []
pip_packages: []
extra_packages_cmds: []

dockitems_remove:
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Pages
  - Photos
  - FaceTime
  - iBooks
  - App Store
  - System Preferences
  - Downloads

dockitems_persist:
  - name: Notes
    path: /Applications/Notes.app
    position: 1
  - name: iTerm
    path: /Applications/iTerm.app
    position: 2
  - name: Fantastical 2
    path: /Applications/Fantastical 2.app
    position: 3
  - name: Google Chrome
    path: /Applications/Google Chrome.app
    position: 4
  - name: Slack
    path: /Applications/Slack.app
    position: 5


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
